language: c
sudo: false
compiler:
  - gcc
  - g++
branches:
  only:
    - master
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - build-essential
      - autoconf
      - automake
      - libtool
      - texinfo
      - xorg-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libncurses-dev
      - libdbus-1-dev
      - libgif-dev
      - libtiff-dev
      - libm17n-dev
      - libpng12-dev
      - librsvg2-dev
      - libotf-dev
      - libxml2-dev
      - libatk-dev
      - libcairo-dev
      - guile2.0-dev
script:
  - ./build-emacs.sh > /dev/null 2>&1
  - ./run-tests.sh
