language: c
sudo: true
compiler:
  - gcc
branches:
  only:
    - master
addons:
  apt:
    packages:
      - gcc-multilib
      - build-essential
      - autoconf
      - automake
      - libtool
      - texinfo
      - xorg-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libncurses-dev
      - libdbus-1-dev
      - libgif-dev
      - libtiff-dev
      - libm17n-dev
      - libpng12-dev
      - librsvg2-dev
      - libotf-dev
      - libxml2-dev
      - libatk-dev
      - libcairo-dev
script:
  - ./build-emacs.sh
  - ./run-tests.sh
